include(CheckCXXCompilerFlag)

function(uni_simd_configure_isa_sources target source_root)
    file(GLOB_RECURSE candidates CONFIGURE_DEPENDS "${source_root}/*.cpp")

    foreach(source IN LISTS candidates)
        get_filename_component(stem "${source}" NAME_WE)
        if(stem MATCHES "_avx2_fma$")
            list(APPEND profile_AVX2_FMA "${source}")
        elseif(stem MATCHES "_avx512bw$")
            list(APPEND profile_AVX512BW "${source}")
        elseif(stem MATCHES "_avx512f$")
            list(APPEND profile_AVX512F "${source}")
        elseif(stem MATCHES "_avx2$")
            list(APPEND profile_AVX2 "${source}")
        elseif(stem MATCHES "_sse2$")
            list(APPEND profile_SSE2 "${source}")
        elseif(stem MATCHES "_neon$")
            list(APPEND profile_NEON "${source}")
        elseif(stem MATCHES "_generic$")
            list(APPEND profile_GENERIC "${source}")
        elseif(stem MATCHES "_common$")
            list(APPEND profile_COMMON "${source}")
        else()
            message(FATAL_ERROR
                "Uni.SIMD source '${source}' has no registered ISA suffix. "
                "Use _common, _generic, _sse2, _avx2, _avx2_fma, _avx512f, _avx512bw, or _neon.")
        endif()
    endforeach()

    set(target_processor "${CMAKE_SYSTEM_PROCESSOR}")
    if(APPLE AND CMAKE_OSX_ARCHITECTURES)
        list(LENGTH CMAKE_OSX_ARCHITECTURES architecture_count)
        if(NOT architecture_count EQUAL 1)
            message(FATAL_ERROR
                "Uni.SIMD requires a single CMAKE_OSX_ARCHITECTURES value. "
                "Build each architecture separately before creating a universal binary.")
        endif()
        list(GET CMAKE_OSX_ARCHITECTURES 0 target_processor)
    endif()
    string(TOLOWER "${target_processor}" target_processor)

    set(target_x86 OFF)
    set(target_aarch64 OFF)
    if(target_processor MATCHES "^(x86_64|amd64|x64|i[3-6]86)$" OR
       MSVC_CXX_ARCHITECTURE_ID MATCHES "^(X86|x64)$")
        set(target_x86 ON)
    elseif(target_processor MATCHES "^(aarch64|arm64)$" OR
           MSVC_CXX_ARCHITECTURE_ID STREQUAL "ARM64")
        set(target_aarch64 ON)
    endif()

    target_sources(${target} PRIVATE ${profile_COMMON} ${profile_GENERIC})
    if(MSVC)
        set_property(SOURCE ${profile_GENERIC} APPEND PROPERTY COMPILE_OPTIONS /fp:strict)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
        set_property(SOURCE ${profile_GENERIC} APPEND PROPERTY COMPILE_OPTIONS -fno-fast-math -ffp-contract=off)
    endif()

    if(target_x86)
        if(MSVC)
            if(CMAKE_SIZEOF_VOID_P EQUAL 8)
                set(have_SSE2 ON)
            else()
                check_cxx_compiler_flag("/arch:SSE2" compiler_has_SSE2)
                set(have_SSE2 ${compiler_has_SSE2})
                set(options_SSE2 /arch:SSE2)
            endif()
            check_cxx_compiler_flag("/arch:AVX2" compiler_has_AVX2)
            check_cxx_compiler_flag("/arch:AVX512" compiler_has_AVX512)
            set(have_AVX2 ${compiler_has_AVX2})
            set(have_AVX2_FMA ${compiler_has_AVX2})
            set(have_AVX512F ${compiler_has_AVX512})
            set(have_AVX512BW ${compiler_has_AVX512})
            set(options_AVX2 /arch:AVX2)
            set(options_AVX2_FMA /arch:AVX2)
            set(options_AVX512F /arch:AVX512)
            set(options_AVX512BW /arch:AVX512)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
            check_cxx_compiler_flag("-msse2" compiler_has_SSE2)
            check_cxx_compiler_flag("-mavx2" compiler_has_AVX2)
            check_cxx_compiler_flag("-mfma" compiler_has_FMA)
            check_cxx_compiler_flag("-mavx512f" compiler_has_AVX512F)
            check_cxx_compiler_flag("-mavx512bw" compiler_has_AVX512BW)
            set(have_SSE2 ${compiler_has_SSE2})
            set(have_AVX2 ${compiler_has_AVX2})
            if(compiler_has_AVX2 AND compiler_has_FMA)
                set(have_AVX2_FMA ON)
            endif()
            set(have_AVX512F ${compiler_has_AVX512F})
            if(compiler_has_AVX512F AND compiler_has_AVX512BW)
                set(have_AVX512BW ON)
            endif()
            set(options_SSE2 -msse2)
            set(options_AVX2 -mavx2)
            set(options_AVX2_FMA -mavx2 -mfma)
            set(options_AVX512F -mavx512f)
            set(options_AVX512BW -mavx512f -mavx512bw)
        endif()
    elseif(target_aarch64)
        set(have_NEON ON)
    endif()

    foreach(profile SSE2 AVX2 AVX2_FMA AVX512F AVX512BW NEON)
        if(have_${profile})
            target_sources(${target} PRIVATE ${profile_${profile}})
            if(options_${profile})
                set_property(SOURCE ${profile_${profile}} APPEND PROPERTY COMPILE_OPTIONS ${options_${profile}})
            endif()
        endif()
        target_compile_definitions(${target} PRIVATE UNI_SIMD_HAVE_${profile}=$<BOOL:${have_${profile}}>)
        set(UNI_SIMD_HAVE_${profile} ${have_${profile}} PARENT_SCOPE)
    endforeach()
endfunction()
